#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages,

sudo apt-get update -y
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo service nginx start
