#!/usr/bin/env bash
# Displays the content of the file /etc/passwd.
FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
  echo "$username:$userid:$comment $homedir"
done < $FILENAME
