#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi

#!/usr/bin/env bash
# This script is displaying "Best School" 10 times.

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	i=$((i+1))
	if [ $i -eq 10 ]
	then
		echo "Hi"
	fi
done
