#!/usr/bin/env bash
# that loops from 1 to 10 and

i=1
while [ $i -lt 11 ]
do
	i=$((i+1))
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
