#!/usr/bin/env bash
# displays: The content of the current directory || n a list format || Where only the part of the name after the first dash is displayed

for file in in *
do
	echo "$file" | cut -d '-' -f 2
done
