#!/usr/bin/env bash
#gives you information about the school file.

x=school
if [ -e "$x" ]
then
	echo "school file exists"
else
	echo "school file does not exist"
fi
if [ -s "$x" ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ -f "$x" ]
then
	echo "school file is a regular file"
fi
