#!/usr/bin/env bash
#gives you information about the school file.

x=school
if [ -e "$x" ]
then
	echo "$x file exists"
else
	echo "$x file does not exist"
fi
if [ -s "$x" ];
then
	echo "$x file is not empty"
else
	echo "$x file is empty"
fi
if [ -f $x ]
then
	echo "$x file is a regular file"
fi
